import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Heading from "./components/Heading";
import dbConnect from "./database/connect";
import Alunos from "./models/Aluno.js";

import React, { useState } from "react";

export const getStaticProps = async () => {
  // Estabelecendo conexão com o banco de dados
  await dbConnect();
  /*
  await Alunos.create({
    Nome: "jeca",
    DataNascimento: Date.now(),
    Ativo: true,
  });
  */
  let data = await Alunos.find({});
  data = JSON.parse(JSON.stringify(data));

  return {
    props: { alunos: data },
  };
};

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "100vh", background: "#151C31" }}>
        <Heading alunos={props.alunos}></Heading>
      </main>
    </div>
  );
}
